### ISSUE TITLE
Cannot change song due to error opening file in /tmp

### ISSUE THREAD

**Issue by ghost** [lucidstack/ctrlp-mpc.vim#2]
Hi, I'm excited about this project, thanks for creating it.

The list of songs shows up perfectly fine. I'm encountering the following error when I try to change the song by pressing `Return`:

```
Error detected while processing function <SNR>154_AcceptSelection..ctrlp#mpc_track#accept:
line 6:
E484: Can't open file /tmp/veMqQFE/30
```

The folder `/tmp/veMqQFE` is owned by my user. I'm using Debian 8, Vim 7.4, mpd 0.19.1-1.1 and mpc 0.26-1. The mpd process is launched by my user.

**Comment by lucidstack** [comment]
Hi there,
Thank you for reporting, and sorry for the issue! I think it's due to me not `shellescape`'ing the arguments to `mpc`. 

[This commit](https://github.com/lucidstack/ctrlp-mpc.vim/commit/8dd7656b3406b966c12c2b32eea2067e563097cf) in master should fix it. When you have a minute, let me know if updating the plugin fixes the problem! :grinning:

**Comment by ghost** [comment]
It works perfectly, thanks for the quick fix! Keep it up!
